"""empty message

Revision ID: 76d1eca6af9f
Revises: 92ce347f5c20
Create Date: 2019-11-24 15:13:06.516200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d1eca6af9f'
down_revision = '92ce347f5c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_good', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_good')
    # ### end Alembic commands ###
